{% set name = "arcos-gui" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e58d120c2e45acc421b86475d3f1900fb46453605baa67dfb5a510142e61ac0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - arcos4py >=0.2.3
    - matplotlib-base >=3.3.4
    - napari >=0.4.15
    - numpy >=1.21.5
    - pandas >=1.3.5
    - python >={{ python_min }}
    - scikit-image >=0.18.1
    - scipy >=1.7.3
    - pyarrow >=11.0.0
    - qtpy

test:
  imports:
    - arcos_gui
    - arcos_gui.widgets
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/bgraedel/arcos-gui
  summary: A napari plugin to detect and visualize collective signaling events
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgraedel
    - goanpeca
    - jaimergp
